// Parses the SQLite DATETIME string format used for every persisted timestamp
// column ('YYYY-MM-DD HH:MM:SS', written by SQLite's own datetime('now',
// 'localtime')) back into a JS Date for API responses. Timestamps are
// generated by SQLite itself at write time, not formatted here - this only
// covers the read-side conversion to ISO 8601 for the REST API.
function parseDateTime(value) {
    const [datePart, timePart] = value.split(' ');
    const [year, month, day] = datePart.split('-').map(Number);
    const [hour, minute, second] = timePart.split(':').map(Number);
    return new Date(year, month - 1, day, hour, minute, second);
}

module.exports = { parseDateTime };
